package simpledb;

import java.util.*;

/**
 * The Join operator implements the relational join operation.
 */
public class HashEquiJoin extends Operator {

    private static final long serialVersionUID = 1L;
    private JoinPredicate p;
    private DbIterator child1;
    private DbIterator child2;
    private transient Map<Field, List<Tuple>> hashMap;
    private transient Tuple tmp2;
    /**
     * Constructor. Accepts to children to join and the predicate to join them
     * on
     * 
     * @param p
     *            The predicate to use to join the children
     * @param child1
     *            Iterator for the left(outer) relation to join
     * @param child2
     *            Iterator for the right(inner) relation to join
     */
    public HashEquiJoin(JoinPredicate p, DbIterator child1, DbIterator child2) {
        this.p = p;
        this.child1 = child1;
        this.child2 = child2;
        this.hashMap = new HashMap<>();
        // some code goes here
    }

    public JoinPredicate getJoinPredicate() {
        // some code goes here
        return p;
    }

    public TupleDesc getTupleDesc() {
        // some code goes here
        return TupleDesc.merge(child1.getTupleDesc(), child2.getTupleDesc());
    }
    
    public String getJoinField1Name()
    {
        // some code goes here
	    return child1.getTupleDesc().getFieldName(p.getField1());
    }

    public String getJoinField2Name()
    {
        // some code goes here
        return child2.getTupleDesc().getFieldName(p.getField2());
    }
    
    public void open() throws DbException, NoSuchElementException,
            TransactionAbortedException {
        super.open();
        child1.open();
        while(child1.hasNext()){
            Tuple tmp = child1.next();
            if(!hashMap.containsKey(tmp.getField(p.getField1()))){
                hashMap.put(tmp.getField(p.getField1()), new ArrayList<Tuple>());
            }
            hashMap.get(tmp.getField(p.getField1())).add(tmp);
        }
        child2.open();
        // some code goes here
    }

    public void close() {
        child1.close();
        child2.close();
        super.close();
        // some code goes here
    }

    public void rewind() throws DbException, TransactionAbortedException {
        child2.rewind();
        // some code goes here
    }

    transient Iterator<Tuple> listIt = null;

    /**
     * Returns the next tuple generated by the join, or null if there are no
     * more tuples. Logically, this is the next tuple in r1 cross r2 that
     * satisfies the join predicate. There are many possible implementations;
     * the simplest is a nested loops join.
     * <p>
     * Note that the tuples returned from this particular implementation of Join
     * are simply the concatenation of joining tuples from the left and right
     * relation. Therefore, there will be two copies of the join attribute in
     * the results. (Removing such duplicate columns can be done with an
     * additional projection operator if needed.)
     * <p>
     * For example, if one tuple is {1,2,3} and the other tuple is {1,5,6},
     * joined on equality of the first column, then this returns {1,2,3,1,5,6}.
     * 
     * @return The next matching tuple.
     * @see JoinPredicate#filter
     */
    protected Tuple fetchNext() throws TransactionAbortedException, DbException {
        // some code goes here
        if(listIt != null && listIt.hasNext()){
            Tuple tmp1 = listIt.next();
            Tuple tmp = tmp1.merge(tmp2);
            return tmp;
        }
        else{
            listIt = null;
        }

        while(child2.hasNext()){
            tmp2 = child2.next();
            if(hashMap.containsKey(tmp2.getField(p.getField2()))){
                listIt = hashMap.get(tmp2.getField(p.getField2())).iterator();
                if(listIt.hasNext()){
                    Tuple tmp = listIt.next().merge(tmp2);
                    return tmp;
                }
            }
        }
        return null;
    }

    @Override
    public DbIterator[] getChildren() {
        // some code goes here
        return null;
    }

    @Override
    public void setChildren(DbIterator[] children) {
        // some code goes here
    }
    
}
